// 130+ ML Heroes with random starting counters
const heroes = [
 { name: "Aamon", description: "Stealth assassin who bursts down squishy enemies", images: "images/aamon.jfif", counters: ["Eudora","Saber","Franco","Kaja"] },
 { name: "Aldous", description: "Late-game fighter who scales with stacks", images: "images/aldous.jfif", counters: ["Chou","Khufra","Kaja"] },
 { name: "Alice", description: "Sustained mage and vampire tank", images: "images/alice.webp", counters: ["Gusion","Helcurt","Lancelot"] },
 { name: "Alpha", description: "Fighter with high mobility and crowd control", images: "images/alpha.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Alucard", description: "Life-stealing melee assassin", images: "images/alucard.jfif", counters: ["Chou","Helcurt","Kaja"] },
 { name: "Angela", description: "Support hero who attaches to allies and heals them", images: "images/angela.webp", counters: ["Gusion","Chou","Helcurt"] },
 { name: "Argus", description: "Fighter with immortality ultimate for diving enemies", images: "images/argus.webp", counters: ["Chou","Kaja","Helcurt"] },
 { name: "Arlott", description: "Marksman with high burst and mobility", images: "images/arlotte.webp", counters: ["Helcurt","Chou","Kaja"] },
 { name: "Atlas", description: "Tank who initiates fights with pulls and stuns", images: "images/atlas.webp", counters: ["Aldous","Khufra","Chou"] },
 { name: "Aulus", description: "Fighter with dash and area damage", images: "images/aulus.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Aurora", description: "Mage with freeze and burst damage", images: "images/aurora.webp", counters: ["Chou","Lancelot","Helcurt"] },
 { name: "Badang", description: "Fighter who chains punches for high damage", images: "images/badang.jpg", counters: ["Chou","Helcurt","Kaja"] },
 { name: "Balmond", description: "Tank/fighter with spin ultimate and sustain", images: "images/balmond.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Bane", description: "Fighter with long-range cannon and lifesteal", images: "images/bane.webp", counters: ["Chou","Helcurt","Kaja"] },
 { name: "Barats", description: "Fighter who grows larger and tankier over time", images:"images/barats.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Baxia", description: "Tank with damage reduction and crowd control", images:"images/baxia.webp" , counters: ["Aldous","Chou","Helcurt"] },
 { name: "Beatrix", description: "Marksman with multiple weapon forms", images: "images/beatrix.webp", counters: ["Helcurt","Chou","Kaja"] },
 { name: "Belerick", description: "Tank with strong crowd control and sustain", images: "images/belerick.webp", counters: ["Aldous","Chou","Helcurt"] },
 { name: "Benedetta", description: "Assassin with dash combos and high mobility", images: "images/benedetta.webp", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Brody", description: "Marksman with high burst damage and poke", images: "images/brody.webp", counters: ["Helcurt","Chou","Kaja"] },
 { name: "Bruno", description: "Marksman with strong single-target skills", images: "images/bruno.webp", counters: ["Helcurt","Chou","Khufra"] },
 { name: "Carmilla", description: "Support mage with drain and root abilities", images:"images/carmilla.webp" , counters: ["Chou","Helcurt","Kaja"] },
 { name: "Cecilion", description: "Long-range mage with strong area damage", images:"images/cecilion.png" , counters: ["Helcurt","Chou","Kaja"] },
 { name: "Chang’e", description: "Mage with moonlight area damage", images:"images/chang'e.jpg" , counters: ["Helcurt","Chou","Khufra"] },
 { name: "Chip", description: "Marksman with strong poke and mobility", images:"images/chip.webp" , counters: ["Chou","Helcurt","Kaja"] },
 { name: "Cici", description: "Mage with strong wave clear and burst", images:"images/cici.webp" , counters: ["Helcurt","Chou","Khufra"] },
 { name: "Chou", description: "Fighter/assassin with knock-up and crowd control", images:"images/chou.webp", counters: ["Aldous","Fanny","Helcurt"] },
 { name: "Claude", description: "Marksman with high mobility and AoE damage", images:"images/claude.webp", counters: ["Helcurt","Chou","Khufra"] },
 { name: "Clint", description: "Marksman with long-range poke and traps", images:"images/clint.jfif" , counters: ["Helcurt","Chou","Kaja"] },
 { name: "Cyclops", description: "Mage with constant burst and blink skills", images:"images/cyclops.jfif" , counters: ["Helcurt","Chou","Khufra"] },
 { name: "Diggie", description: "Support with anti-CC and map control", images:"images/diggie.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Dyrroth", description: "Fighter with burst and mobility", images:"images/dyrroth.jfif" , counters: ["Chou","Helcurt","Kaja"] },
 { name: "Edith", description: "Marksman with high single-target damage", images:"images/edith.webp" , counters: ["Chou","Helcurt","Khufra"] },
 { name: "Esmeralda", description: "Fighter/mage who absorbs shields", images:"images/esmeralda.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Estes", description: "Support healer with AoE sustain", images:"images/estes.webp" , counters: ["Chou","Helcurt","Kaja"] },
 { name: "Eudora", description: "Burst mage with stun combo", images:"images/eudora.jfif" ,  counters: ["Helcurt","Chou","Khufra"] },
 { name: "Fanny", description: "High mobility assassin with cables", images: "images/fanny.webp", counters: ["Khufra","Franco","Minsitthar"] },
 { name: "Faramis", description: "Support/mage who revives allies", images:"images/faramis.webp", counters: ["Chou","Kaja","Helcurt"] },
 { name: "Floryn", description: "Support healer with shield and utility", images:"images/floryn.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Franco", description: "Tank with hook and crowd control", images:"images/franco.jfif", counters: ["Aldous","Chou","Khufra"] },
 { name: "Fredrinn", description: "Fighter/assassin with mobility", images:"images/fredrinn.webp", counters: ["Chou","Helcurt","Kaja"] },
 { name: "Freya", description: "Fighter with ranged grab and ultimate", images:"images/freya.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Gatotkaca", description: "Tank/fighter with knock-up ultimate", images:"images/gatotkaca.webp", counters: ["Aldous","Chou","Helcurt"] },
 { name: "Gloo", description: "Tank with damage absorption and poke", images:"images/gloo.webp" , counters: ["Aldous","Khufra","Chou"] },
 { name: "Gord", description: "Mage with long-range poke and AoE damage", images:"images/gord.webp" , counters: ["Helcurt","Chou","Kaja"] },
 { name: "Granger", description: "Marksman with burst and mobility", images:"images/granger.webp" , counters: ["Helcurt","Karina","Chou"] },
 { name: "Grock", description: "Tank with wall and high damage", images:"images/grock.jfif", counters: ["Aldous","Chou","Khufra"] },
 { name: "Guinevere", description: "Fighter/mage with crowd control",images: "images/guinevere.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Gusion", description: "Assassin with high burst and combos", images:"images/gusion.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Hanabi", description: "Marksman with AoE damage and poke", images:"images/hanabi.webp", counters: ["Helcurt","Karina","Lancelot"] },
 { name: "Hanzo", description: "Assassin with shuriken burst", images:"images/hanzo.webp", counters: ["Khufra","Chou","Lancelot"] },
 { name: "Harith", description: "Assassin/mage with dash combos", images:"images/harith.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Harley", description: "Mage/assassin with strong burst", images:"images/harley.webp", counters: ["Khufra","Chou","Lancelot"] },
 { name: "Hayabusa", description: "Assassin with shadow clones and burst", images:"images/hayabusa.webp", counters: ["Khufra","Chou","Lancelot"] },
 { name: "Helcurt", description: "Assassin with silence and burst", images:"images/helcurt.webp", counters: ["Khufra","Chou","Lancelot"] },
 { name: "Hilda", description: "Fighter/tank with sustain and dive", images:"images/hilda.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Hylos", description: "Tank/fighter with AoE and mobility", images:"images/hylos.jfif", counters: ["Aldous","Chou","Lancelot"] },
 { name: "Irithel", description: "Marksman with high mobility and damage", images:"images/irithel.webp", counters: ["Helcurt","Karina","Lancelot"] },
 { name: "Ixia", description: "Mage with high burst and zoning", images:"images/ixia.webp" , counters: ["Chou","Khufra","Lancelot"] },
 { name: "Jawhead", description: "Fighter/tank with throw and stun", images:"images/jawhead.webp" , counters: ["Chou","Khufra","Lancelot"] },
 { name: "Johnson", description: "Tank with dash and crowd control", images:"images/johnson.webp" , counters: ["Aldous","Chou","Lancelot"] },
 { name: "Joy", description: "Fighter/assassin with high mobility", images:"images/joy.jfif", counters: ["Chou","Karina","Lancelot"] },
 { name: "Julian", description: "Marksman with strong burst and poke", images:"images/julian.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Kadita", description: "Mage with water skills and AoE damage", images:"images/kadita.jfif", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Kagura", description: "Mage with umbrella burst and poke", images:"images/kagura.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Kaja", description: "Fighter/support with pull and stun", images:"images/kaja.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Kalea", description: "Mage with burst combos", images:"images/kalea.jfif", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Karina", description: "Assassin with burst and stealth", images:"images/karina.webp", counters: ["Khufra","Chou","Lancelot"] },
 { name: "Karrie", description: "Marksman with anti-tank damage", images:"images/karrie.webp" , counters: ["Helcurt","Chou","Lancelot"] },
 { name: "Khaleed", description: "Fighter with dash and AoE", images:"images/khaleed.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Khufra", description: "Tank with knock-up and crowd control", images:"images/khufra.webp" , counters: ["Aldous","Chou","Lancelot"] },
 { name: "Kimmy", description: "Marksman/mage with long-range poke", images:"images/kimmy.webp", counters: ["Helcurt","Chou","Lancelot"] },
 { name: "Lancelot", description: "Assassin with high mobility and burst", images:"images/lancelot.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Lapu-Lapu", description: "Fighter/assassin with dual forms", images:"images/lapu-lapu.webp", counters: ["Chou","Khufra","Lancelot"] },
 { name: "Layla", description: "Marksman with high range and poke", images: "images/layla.webp", counters: ["Helcurt","Lancelot","Chou"] },
 { name: "Leomord", description: "Fighter with horse form for high mobility and damage", images:"images/leomord.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Lesley", description: "Marksman with sniper skills and stealth", images:"images/lesley.jfif", counters: ["Helcurt","Chou","Khufra"] },
 { name: "Ling", description: "Assassin with wall-crossing mobility and burst", images:"images/ling.webp", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Lolita", description: "Tank with shield and crowd control", images:"images/lolita.webp", counters: ["Aldous","Chou","Helcurt"] },
 { name: "Lukas", description: "Fighter with high mobility and burst damage using his Bloodless Energy", images:"images/lukas.webp", counters: ["Chou", "Helcurt", "Khufra"] },
 { name: "Lunox", description: "Mage with light and dark forms for burst and sustain", images:"images/lunox.webp", counters: ["Chou","Helcurt","Khufra"] },
 { name: "Luo Yi", description: "Mage with teleportation and AoE burst", images:"images/luoyi.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Lylia", description: "Mage with high mobility and area damage", images:"images/lylia.webp", counters: ["Helcurt","Chou","Kaja"] },
 { name: "Masha", description: "Fighter with high HP and damage mitigation", images:"images/masha.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Mathilda", description: "Support/fighter with mobility and buffs", images:"images/mathilda.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Martis", description: "Fighter with AoE spins and stun abilities", images:"images/martis.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Melissa", description: "Marksman/mage hybrid with burst skills", images:"images/melissa.jfif", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Minotaur", description: "Tank with crowd control and sustain", images:"images/minotaur.webp", counters: ["Aldous","Chou","Helcurt"] },
 { name: "Minsitthar", description: "Fighter/tank with crowd control ultimate", images:"images/minsitthar.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Miya", description: "Marksman with rapid-fire attacks and AoE", images:"images/miya.webp" , counters: ["Helcurt","Chou","Lancelot"] },
 { name: "Moskov", description: "Marksman with piercing spear and mobility", images:"images/moskov.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Nana", description: "Support/mage with crowd control and polymorph", images:"images/nana.webp", counters: ["Chou","Helcurt","Kaja"] },
 { name: "Natalia", description: "Assassin with stealth and high burst", images:"images/natalia.jpg", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Natan", description: "Marksman/mage hybrid with AoE burst", images:"images/natan.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Nolan", description: "Fighter/mage with dash combos and AoE", images:"images/nolan.jfif", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Novaria", description: "Mage with long-range AoE and zoning skills", images:"images/novaria.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Obsidia", description: "Fighter/assassin with burst combos", images:"images/obsidia.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Odette", description: "Mage with swan-themed AoE burst damage", images:"images/odette.webp", counters: ["Helcurt","Chou","Lancelot"] },
 { name: "Paquito", description: "Fighter with boxing combos and mobility", images:"images/paquito.jfif", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Pharsa", description: "Mage with high-range AoE ultimate", images:"images/pharsa.webp" , counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Phoveus", description: "Fighter with dive abilities and sustain", images:"images/phoveus.webp" , counters: ["Khufra","Chou","Helcurt"] },
 { name: "Popol and Kupa", description: "Marksman duo with pets and control", images:"images/popolandkupa.jfif", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Rafaela", description: "Support healer with speed boost and sustain", images:"images/rafaela.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Roger", description: "Fighter/marksman with dual forms", images:"images/roger.webp", counters: ["Helcurt","Chou","Lancelot"] },
 { name: "Ruby", description: "Fighter with lifesteal and crowd control", images:"images/ruby.jfif", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Saber", description: "Assassin with teleport and burst skills", images:"images/saber.jfif", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Selena", description: "Assassin/mage with traps and burst combos", images:"images/selena.jfif", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Silvanna", description: "Fighter with spear AoE and crowd control", images:"images/silvanna.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Sora", description: "Marksman/mage hybrid with ranged skills", images:"images/sora.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Sun", description: "Fighter with clones and AoE damage", images:"images/sun.webp" , counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Suyou", description: "Assassin/fighter with high mobility and burst", images:"images/suyou.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Terizla", description: "Fighter/tank with AoE and sustain", images:"images/terizla.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Thamuz", description: "Fighter with burn damage and crowd control", images:"images/thamuz.webp", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Tigreal", description: "Tank with crowd control and initiation", images:"images/tigreal.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Uranus", description: "Tank with fast regen and sustain", images:"images/uranus.jfif", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Vale", description: "Mage with wind AoE and control", images:"images/vale.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Valentina", description: "Mage/assassin who can steal skills", images:"images/valentina.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Valir", description: "Mage with fire AoE and poke", images:"images/valir.webp" , counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Vexana", description: "Mage with undead summons and damage over time", images:"images/vexana.webp" , counters: ["Khufra","Chou","Helcurt"] },
 { name: "Wanwan", description: "Marksman with dash and multi-hit ultimate", images:"images/wanwan.webp" , counters: ["Chou","Helcurt","Lancelot"] },
 { name: "X.Borg", description: "Fighter with explosive projectiles and dash", images:"images/x.borg.webp" , counters: ["Chou","Khufra","Helcurt"] },
 { name: "Xavier", description: "Support/mage with shields and poke", images:"images/xavier.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Yi Sun-Shin", description: "Marksman/assassin with global attacks", images:"images/yisunshin.webp", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Yin", description: "Assassin/fighter with burst and mobility", images:"images/yin.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Yu Zhong", description: "Fighter with dragon form and sustain", images:"images/yuzhong.webp", counters: ["Chou","Khufra","Helcurt"] },
 { name: "Yve", description: "Mage with long-range control and poke", images:"images/yve.webp", counters: ["Chou","Helcurt","Lancelot"] },
 { name: "Zhask", description: "Mage/summoner with turret minions", images:"images/zhask.webp", counters: ["Khufra","Chou","Helcurt"] },
 { name: "Zetian", description: "Mage with powerful long‑range abilities and burst potential",  images:"images/zetian.webp" , counters: ["Chou", "Helcurt", "Khufra"]  },
 { name: "Zhuxin", description: "Marksman with high mobility and potent burst attacks", images:"images/zhuxin.webp" , counters: ["Helcurt", "Chou", "Khufra"] },
 { name: "Zilong", description: "Fighter/assassin with spear and high mobility", images:"images/zilong.webp" , counters: ["Chou","Helcurt","Lancelot"] },
 
];

console.log("Total heroes:", heroes.length);
